package model

const (
	StartCommand               = "start"
	FakeCommand                = "fake"
	HoneyPotCommand            = "honeypot"
	NFTCommand                 = "nfts"
	ListCommand                = "list"
	ListNFTsCommand            = "listnfts"
	ListNFTsByNameCommand      = "listnftsbyname"
	ListNFTsDefaultCommand     = "listnftsdefault"
	JettonsCommand             = "jettons"
	ListJettonsCommand         = "listjettons"
	ListJettonsByNameCommand   = "listjettonsbyname"
	ListJettonsDefaultCommand  = "listjettonsdefault"
	JetttonNewPoolsCommand     = "24hjetttonnewpools"
	FakeAccountCommand         = "fakeaccount"
	ListAccountsCommand        = "listaccounts"
	ListAccountsByNameCommand  = "listaccountsbyname"
	ListAccountsDefaultCommand = "listaccountsdefault"
	FakeJettonCommand          = "fakejetton"
	FakeNFTCommand             = "fakenft"
	JettonHolderCommand        = "jettonholder"
	JettonChangesCommand       = "24hjettonchanges"
	JettonAmountCommand        = "24hjettonamounts"
	JettonTopHoldersCommand    = "jettontop10"
	JettonBalanceCommand       = "jettonbalance"
	NFTCollectionCommand       = "nftcollection"
	NFTItemCommand             = "nftitem"
	NFTAssetCommand            = "nftasset"
	HelpCommand                = "help"
)
